### ISSUE TITLE
Feature request: expose trailers from GrpcError

### ISSUE THREAD

**Issue by TinoGuo** [grpc/grpc-dart#135]
Until now, it seems GrpcError can only receive the normal error. But grpc-java can receive trailers from StatusRuntimeException just like class GrpcError.

I need to get the trailers from GrpcError to deal business logic.

version: 0.6.6

**Comment by njovy** [comment]
Trailers feature is still missing. Any plan on this?

**Comment by jonasbeyer** [comment]
Any updates on this? 

gRPC-Java doesn't support custom error codes, so I decided to make use of the response metadata to implement the client-side error handling. Unfortunately, this is not supported by gRPC-Dart.

It would be really helpful if both libraries used the same approach.

**Comment by ejona86** [comment]
grpc-java does not generally expose metadata to applications. Trailers do seem to be supported in grpc-dart and are exposed directly, so it shouldn't be as necessary to be part of the error. I'll note that Java's put-metadata-on-the-exception is unlike most implementations. But the practice of putting custom error information in the trailers is appropriate cross-language.

Since the stub returns a call object, you can simply delay the `await` and register a trailers callback (and _then_ await the call).

https://github.com/grpc/grpc-dart/blob/27d9164f28dc9d090e0ad81384034049633ca5e3/example/metadata/lib/src/client.dart#L52-L55

**Comment by kengu** [comment]
@ejona86 The problem with requiring clients to depend on the actual client call instance to fetch trailers, is that this object is not readily available in for example in client interceptors. In client interceptors, only the response future or stream is exposed, making it impossible handle errors when required information to handle them correctly is located in trailers. Other [implementations like csharp](https://grpc.github.io/grpc/csharp/api/Grpc.Core.RpcException.html#Grpc_Core_RpcException_Trailers) have trailers available in the exception thrown by the client for this reason.

**Comment by kengu** [comment]
PR #489 does not solve this problem either, since ClientCall is not exposed.
