### ISSUE TITLE
gRPc and FLUTTER/DART on OSx.  can it work?

### ISSUE THREAD

**Issue by vinceyoumans** [grpc/grpc-dart#138]
I posted this quesiton on StackOverflow...  https://stackoverflow.com/questions/53462092/grpc-protocol-buffers-and-flutter-on-osx

I'd like to use gRPC / ProtoBuffers between a Flutter/Dart app developed on OSx and a GoLang server. My thought is to replace a REST connection. My problem is that I cannot install Protobuf on OSx for DART.... or at least, I can't seem to figure it out.
This URL, towards the end, says that Protobuf for DART is only supported for Ubuntu.https://chromium.googlesource.com/external/github.com/google/protobuf/+/HEAD/README.md

QUESTIONS

Is this correct that Protobuf on OSx for Dart Flutter is not working yet?
Any tips or tricks to make it work? and I missing something here?

**Comment by sigurdm** [comment]
We have no reason to believe it works different on OS-X than on linux.
We do not have a Travis build bot for it, but everything should basically work the same (after installing protoc).

On Windows there is an issue with using the protobuf plugin together with protoc. That should be fixed with the release of 3.6.1.

I would suggest to try it out, and open a new issue if you run into problems.
