### ISSUE TITLE
in android use secure

### ISSUE THREAD

**Issue by qiuguian** [grpc/grpc-dart#225]
run in ios is no error but run in android use flutter,thent got error:Error connecting: HandshakeException: Handshake error in client (OS Error:
I/flutter ( 8621): CERTIFICATE_VERIFY_FAILED: self signed certificate(handshake.cc:352))

**Comment by pkkhandsome** [comment]
Use secure to ensure several issues
1. The difference between local time and network time is more than 15 days.
2. The certificate expired.

Note: IOS 13 has updated the certificate rules and has stricter certificate requirements.

Grpc 2.0 version Modify some things:
If the authority and host are inconsistent, the certificate verification will fail.
So in order to fix this problem:

/lib/src/client/http2_connection.dart , line 84.

`socket = await SecureSocket.connect(host, port,
          supportedProtocols: ['h2'],
          context: securityContext,
          onBadCertificate: _validateBadCertificate);`

change to

`socket = await Socket.connect(host, port);
      socket = await SecureSocket.secure(socket,
          host: authority,
          context: securityContext,
          onBadCertificate: _validateBadCertificate);`

**Comment by sigurdm** [comment]
This should be fixed in 2.1.1 .
Please reopen if I'm mistaken.
Thanks!
