### ISSUE TITLE
Is grpc-dart production ready

### ISSUE THREAD

**Issue by ansarizafar** [grpc/grpc-dart#281]
grpc is a great option for Dart/Flutter apps but it seems its not production ready. There are performance issues and  missing features. I would request Dart team to invest more time to make it production ready as soon as possible.

**Comment by supermuka** [comment]
Hi Zafar, I am using grpc-dart in production. All code in Dart. AngularDart + grpc_web in client side and grpc in server side.

**Comment by ansarizafar** [comment]
@supermuka Check this https://github.com/grpc/grpc-dart/issues/249

**Comment by ansarizafar** [comment]
@supermuka There are so many opened issues and It seems that no one from the core team is replying.

**Comment by supermuka** [comment]
My intention was just to say that I am using it as it is in a production application.

I need to agree with you, there are points to improve! I may be wrong, but it seems to me that every time a project/package from the Dart ecosystem is no longer new/novelty (Flutter is now. But Server-side, AngularDart, Rpc, Grpc, etc. it seems to be no more) the Google Dart Team stops maintaining it. At least it is difficult to find any official position of the leaders regarding the future of many dart-team packages.

If this is true, it is really sad, because a language and its ecosystem will have traction and trust of the engineers only if there are constant improvements in all ecosystem official components.

**Comment by mit-mit** [comment]
Thanks for the question and feedback. The package is not complete (there are still a number of outstanding enhancement requests), and like any other piece of software we also have some issues. For a period we were not able to keep up with incoming issues and PRs due to personnel issues, but we're taking steps to improve. 

About the more general question about Dart packages, we're actually going through an internal process right now of bucketing our hundreds of packages into a number of tiers so that we can more clearly communicate what you can expect from each of them.
