### ISSUE TITLE
command failed: Can't load Kernel binary: Invalid kernel binary format version.

### ISSUE THREAD

**Issue by artoniaz** [grpc/grpc-dart#395]
<short description>
Hey,
I'm trying to follow this docs to create gRPC client: https://docs.servicestack.net/grpc-flutter

When I try to Add protoc generated TodoWorld DTOs and gRPC GrpcServiceClient to lib/ folder:
`x proto-dart https://todoworld.servicestack.net -out lib`

I get error:
`Updated: services.proto
`protoc -I . -I "/home/deploy/apps/protoc-api/protoc/include" --dart_out=grpc:out services.proto` command failed: Can't load Kernel binary: Invalid kernel binary format version.
No active package protoc_plugin.
--dart_out: protoc-gen-dart: Plugin failed with status code 65.
`
I've been looking for an anwear for a long time, but I can't find anything useful. 
I do have protoc_plugin installed globally from here https://pub.dev/packages/protoc_plugin.
I also tried to `flutter pub global activate fvm` 

I'm on beta channel if it's important but the issue is the same on stable

Please help :)

**Comment by mraleph** [comment]
You most likely have some old `dart` binary in your PATH which is not the same as `dart` binary which you use to run pub (e.g. if you do `flutter pub global activate protoc_plugin` you use `dart-sdk` from `flutter` installation).

I think you have two choices: 

- Do `which dart` and remove that dart installation. Then add `$flutter/bin/cache/dart-sdk/bin` to `PATH`.

- Remove your `.pub-cache` then do `pub global activate protoc_plugin` (note no `flutter`) - so that you use `dart` binary from the `PATH`.
