### ISSUE TITLE
Async $onMetadata

### ISSUE THREAD

**Issue by ruicraveiro** [grpc/grpc-dart#401]
I would like to be able to perform async operations on the $onMetadata event. Currently this method returns void and doesn't support async. My purpose is to retrieve a Jwt token from the request headers, but instead of overloading the Jwt token, I intend to get the rest of the user information from the database and build a principal from there. The idea method for this would be $onMetadata, except for the fact that its caller isn't expecting a Future, so it will not await for the call to the database before continuing and calling the grpc method.

My starting point is version 2.8.0

## Repro steps

1. Add a $onMetadata method to a service, with an async operation, like for example:
```Dart
  Principal _principal;

  Future $onMetadata(ServiceCall context) async {

    _principal = null;
    var jwtPayload = getJwtFromContext(context);

    _principal = await getPrincipalFromDatabase(jwtPayload);
  }
```

2. Implement a method that looks at the _principal field.

Actual and expected result: What is happening now, as expected, is that _principal will be null when the method on 2. is called, because that method will be called before the getPrincipalFromDatabase(jwtPayload) call is finished awaiting.

Desired result: The async method would have been awaited and on the service method, the resulting value should be available, instead of null.

I have a proposed change to handler.dart and a few tests that I will submit as a pull request that, if accepted, will add this feature.

**Comment by mraleph** [comment]
I would like to understand your motivating example a bit, because it seems a bit broken to me: 

```dart
  Principal _principal;

  Future $onMetadata(ServiceCall context) async {

    _principal = null;
    var jwtPayload = getJwtFromContext(context);

    _principal = await getPrincipalFromDatabase(jwtPayload);
  }
```

It seems to me that you can't really use a field on the service to store the principal because you can receive two concurrent calls with different JWT tokens - in this case one of them might end up using the wrong principal from the other call. This seems wrong. 

In any case I am not sure I understand why you would like to do it in `$onMetadata`. Your service call handler also has access to `ServiceCall` - why not just do it there? I would just do it like this: 

```dart
  Future<Principal> principalOf(ServiceCall context) {
    final jwtPayload = getJwtFromContext(context);
    return getPrincipalFromDatabase(jwtPayload);
  }

  Future<HelloReply> sayHello(ServiceCall call, HelloRequest request) async {
    final principal = await principalOf(call);
    // The rest of the call. 
  }
```

That's a bit more typing then you have now - but your current implementation is likely incorrect as noted above due to concurrency issues. 

The only way to make `$onMetadata` approach work _and_ require less typing is probably refactor things to allow attaching arbitrary payloads to `ServiceCall` objects. I don't think this is really needed though.

**Comment by ruicraveiro** [comment]
Since Dart is using Isolates instead of threads, isn't concurrency supposed to be a non-issue? The reason why I rejected your approach is because it is not reusable. If my service has several methods (a typical CRUD service will have at least 4 methods, then I need to pollute it with authentication everywhere. Implementing things on the $onMetadata allows me to have a Mixin that implements that method and simply plug it into every service I want to authenticate. Leaving authentication and authorization to each and every method is a disaster waiting to happen. Murphy's law will make it guaranteed that there will be at least one method where I failed to check for the principal, meaning a security hole. I could decode the Jwt header in $onMetadata and verify it there just to be sure the user is authenticated (in a very centralized, safe and reusable place) and then grab the principal in sayHello, but without data sharing via ServiceCall, this means decoding the Jwt all over again, which is wasteful.

This leaves us with the possibility to attach arbitrary data to ServiceCall. I actually did consider that approach, but stopped short only because I assumed the non-concurrent nature in Dart. However, I do like the solution where I do get the principal in $onMetadata for every call, but still be able to retrieve it via ServiceCall. Is it OK if I change the pull request to include that?

**Comment by ruicraveiro** [comment]
Since it turned out to be exceedingly easy, I have just added a commit to the pull request that includes a new field to ServiceCall. Is this OK with you?
- I called it customData, but I don't really mind to change it to any other name.
- I typed it as Object, but I am not really sure if it would make more sense to have it as dynamic.

**Comment by mraleph** [comment]
> Since Dart is using Isolates instead of threads, isn't concurrency supposed to be a non-issue? 

Concurrency is still an issue. If you have a straight line Dart code (no async) then it is guaranteed to run to completion with no other Dart code interleaving with it. However when you have async code (e.g. you use futures/streams callbacks or async/await) then execution can interleave. Try running this:

```dart
Future<void> foo() async {
    print('foo 1');
	await null;
    print('foo 2');
	await null;
    print('foo 3');
}

Future<void> bar() async {
    print('bar 1');
	await null;
    print('bar 2');
	await null;
    print('bar 3');
    await null;
}

void main() async {
  await Future.wait([foo(), bar()]);
}
```

You will see that execution of `foo` and `bar` interleaves. Hence you still need to consider how you interact with your data if it is stored in shared static state.

Now regarding storing information on `ServiceCall`. To be honest, it is not entirely clear to me if it is really needed, because you can just do this: 

```dart
extension MyPrincipal on ServiceCall {
  static Expando _storage = Expando();
  Future<Principal> get principal {
    return _storage[this] ??= authenticate(this);
  }
}
```

Now, if you want to enforce that all calls are authenticated then you just do this:

```dart
FutureOr<GrpcError> authInterceptor(ServiceCall call, ServiceMethod method) {
  final principal = await call.principal;
  if (principal == null) {
    throw GrpcError.permissionDenied();
  }
  // Continue with the call.
}

final server = Server(..., [authInterceptor]);
```

So it seems all necessary pieces are already there and no changes are really needed.

**Comment by ruicraveiro** [comment]
I stand corrected concerning concurrency. Let me check out the Expando approach. Maybe that will be enough, indeed. 

However, I did consider the interceptor, but it turned out not to be the solution for my business case, for several reasons:

- I still need to get the principal from some service methods (not all), but without having to reparse the Jwt token all over again, so it presents the exact same problem the $onMetadata approach does. The only advantage the interceptor has is that is already async. So, either using the $onMetadata approach or the interceptor, the problem of data sharing is pretty much the same.

- I really need the decision of whether to authenticate to be done on a per-service level, not on a global level. I didn't find an easy way on the interceptor to determine the service being called (maybe because I am still learning this framework). However, even if I found I wouldn't want to create an interceptor with ifs to determine which services would require user authentication, which wouldn't. The correct place to put that code is in the service itself (regardless of how I do it, either by implementing $onMetadata on each service, by including a Mixin with the implementation or on each method).

Anyhow, if the Expando can be slow, why not accept the customData field?

**Comment by ruicraveiro** [comment]
The Expando approach works. :-)

So, what I am doing is the following. 

1. The extension splits its functions into two parts. The jwtPayload property parses or gets the parsed token from the Expando. This is the authentication part, where I get to determine the user. This property is sync as what it does is mostly processing. The principal property reuses the jwtPayload property and goes to the database to get the rest of the user information. This relates to authorization as what I want to get from the database is mostly roles, permissions, and so on.

```Dart
/// imports

extension AuthenticationExtensions on ServiceCall {
  static final Expando _storage = Expando();

  Future<Principal> get principal async {
    final user = await getUserFromPayload(jwtPayload);
    final ret = Principal(user);
    return ret;
  }

  JwtPayload get jwtPayload {
    return _storage[this] ??= _authenticate();
  }

  JwtPayload _authenticate() {
    var token = clientMetadata['authorization'];
    // parses the token and returns JwtPayload or throws GrpcError.unauthenticated is the token is not existing or invalid.
  }
}

```

2. Per service authentication becomes viable to be done on a sync $onMetadata:
```Dart
  void $onMetadata(ServiceCall context) {
    context.jwtPayload; // will throw if there isn't a valid token. Will store jwtPayload in Expando if token is valid.
  }
```

3. My service methods then will use the async principal property if needed, like for instance the generic create method I have in my Mixin:
```Dart
  Future<TProto> create(ServiceCall call, TProto proto) async {
    var builder = builderProtoMapper.fromProto(proto);

    builder.meta = EntityMetaBuilder()
      ..tenantId = (await call.principal).tenantId // the principal is also used for ownership and multi-tenancy
                                                                         // the part where the token was parsed, however, is
                                                                         // reused from the call to $onMetadata
      ..revisions = [await createRevision(call)];

   /// rest of the implementation
 }

```

I have tested and this all works nicely. Thank you! :-D

Having that said, will you accept a new pull request that only adds the ServiceCall.customData property to avoid the Expando performance penalty?

**Comment by mraleph** [comment]
> Having that said, will you accept a new pull request that only adds the ServiceCall.customData property to avoid the Expando performance penalty?

Well, it depends. I think I'd want to investigate how other grpc implementation handle the same problem first and then implement a solution which is aligned in terms of APIs.

This would require us to invest some time into this - and right now I am not sure I can afford this personally as there are other high priority things to tend to. 

Given that your immediate needs are right now addressed, I am going to close this issue. We can revisit this at some later stage, either if current solution turns out unsatisfactory or if we suddenly get an engineer working on grpc-dart

**Comment by ruicraveiro** [comment]
Microsoft added this property to .net's Grpc implementation:

        // Summary:
        //     Gets a dictionary that can be used by the various interceptors and handlers of
        //     this call to store arbitrary state.
        public IDictionary<object, object> UserState { get; }
