### ISSUE TITLE
The uri in the metadataProvider function is not full path

### ISSUE THREAD

**Issue by songfei** [grpc/grpc-dart#417]
https://github.com/grpc/grpc-dart/blob/c48af638a54225fe39200df726440ac7bde4225c/lib/src/client/call.dart#L255

```
// TODO(sigurdm): Find out why we do this.
  static String audiencePath(ClientMethod method) {
    final lastSlashPos = method.path.lastIndexOf('/');
    return lastSlashPos == -1
        ? method.path
        : method.path.substring(0, lastSlashPos);
  }
```

why do this?

**Comment by mraleph** [comment]
Apparently this parameter was added when JWT authentication was added and JWT token generation needs service uri, rather than full method uri - so the code was written to strip method name from the path. 

See https://github.com/grpc/grpc-dart/pull/55/files for context. 

I think this was done strangely and instead method name should have probably been stripped by the metadata provider itself. 

But changing it now would be a breaking change because people might be already relying on the current behaviour.
