### ISSUE TITLE
[Question] Pass url to ClientChannel

### ISSUE THREAD

**Issue by BatanGaming** [grpc/grpc-dart#468]
Is there any way to pass url to `ClientChannel` constructor as `host`?

So, I have multiple "stands" for testing with urls like `/stand1`, `/stand2`, etc. So, I wonder if there is any way to pass url like `localhost/stand1`? 

Now I have this error

```
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: gRPC Error (code: 14, codeName: UNAVAILABLE, message: Error connecting: SocketException: Failed host lookup: 'localhost/stand1' (OS Error: nodename nor servname provided, or not known, errno = 8), details: null, rawResponse: null)
```

**Comment by mraleph** [comment]
I don't think we can make this work. 

This has been requested before in context of gRPC-Web (#258), where we might make it work, but gRPC over HTTP2 protocol as specified does not allow such sort of prefixing (because `:path` should contain service name followed by the method name).

It seems canonical approach for having multiple gRPC servers served through a single HTTP server is to use `:authority` instead, see https://github.com/grpc/grpc/issues/14900
