### ISSUE TITLE
GrpcOrGrpcWebClientChannel   grpcport and grpcWebPort  must not be prevented to be the same.

### ISSUE THREAD

**Issue by gustav3d** [grpc/grpc-dart#482]
I'ts false assumption that there need to be two different ports, and preventing to use the same port makes it not work with standard configuration for GRPC AspNetCore server.

**Comment by mraleph** [comment]
Feel free to submit a PR.

**Comment by gustav3d** [comment]
Feel free to fix your own flawed design. Dont expect others to do it for you.

**Comment by mraleph** [comment]
I understand you frustration, but you should understand that this repo is not really actively maintained. I am reviewing PRs and keeping things somewhat afloat more or less out of sense of responsibility. Protocols are also rather remote from my area of expertise (which is compiler contruction), so understandably I have no way of knowing that there are gRPC servers that serve both grpc and grpc-web protocols on the same port. 

Hence if you want something to be fixed, you shortest path is to fix it yourself. 

Alternatively, others (maybe @morgwai who contributed the original code) can fix it. So lets keep it open.

**Comment by morgwai** [comment]
I wasn't aware about this either: all the docs I've seen were clearly stating that these are separate protocols. I assumed that this was not possible due to the fact that gRPC does not seem to have a notion of request-path prefix.
@gustav3d  Could you explain or link to some docs that explain how this is achieved? I'd be eager to understand it ;-)

A fix for this is quite trivial: remove 1 line that does the check. Actually it's 2 lines as there are 2 versions for web platform and for others ;-)
https://github.com/grpc/grpc-dart/blob/master/lib/src/client/grpc_or_grpcweb_channel_grpc.dart#L36
https://github.com/grpc/grpc-dart/blob/master/lib/src/client/grpc_or_grpcweb_channel_web.dart#L28

**Comment by morgwai** [comment]
draft: https://github.com/grpc/grpc-dart/pull/483

**Comment by mraleph** [comment]
I'd guess that middleware can detect protocol type by peaking at `Content-Type` header, which is different for these two protocols.

**Comment by mraleph** [comment]
Fixed by @morgwai ! Thanks!

**Comment by morgwai** [comment]
@mraleph thanks for the review!
@gustav3d  thanks for pointing the issue!
