### ISSUE TITLE
Question|Feature: Sending Binary Metadata

### ISSUE THREAD

**Issue by nevi-me** [grpc/grpc-dart#72]
The grpc spec allows for sending `metadata-bin` as binary metadata. Is this currently supported?

v0.4.0

## Repro steps

1. Create a grpc-dart client to connect to a server

1. Create a client call including a binary metadata key with a text value

```dart
    channel.stub.myMethod(new Request(), options: new CallOptions(metadata: {
      "testmetadata": "a string",
      "testmetadata-bin": "supposed to be binary"
    }, timeout: new Duration(seconds: 15))).then((Response response) {
      print(response);
    }).catchError((GrpcError error) {
      print("******* ${error.message} ******");
    });
```

Expected result: The request should either throw an error about malformed `*-bin` metadata, or discard the metadata

Actual result: The request sends the metadata, but there's a failure on the server (tested with NodeJS and Java)

## Details

The request seems to silently fail on both NodeJS and Java, I tried getting log output, but couldn't find anything. I use nghttpx as my proxy, and it passed the `testmetadata-bin` as I supplied it.

One of the reasons why I use binary metadata is to pass my custom error messages as protobuf messages. I suppose it's a question for another day, but how would I deal with bytedata in dart? Do I use `Uint8List`?

**Comment by nevi-me** [comment]
I forgot to mention, removing the binary metadata field results in a successful call. 

As a side note, flutter with gRPC is a dream so far! I'm rewriting an Android app that I gave up on after over a month, and within 2 days, I'm about 70% done with the same spec app using Flutter!

**Comment by gedw99** [comment]
+1. i need this too. Prefer not ot have to base64 it :)

**Comment by nevi-me** [comment]
@gedw99 from my understanding, you can successfully send binary metadata, the library doesn't yet go the extra mile of checking whether a `*-bin` contains binary data, but it shouldn't stop us from using binary metadata.

**Comment by gedw99** [comment]
Ah. Not so bad..any chance you can link to an example of sniffing for this
from a dart function ?

**Comment by njovy** [comment]
Any new update regarding this?

**Comment by mraleph** [comment]
I am going to close this issue to reflect that no special work is planned here. There is nothing preventing you from sending binary metadata, you just need to base64 encode it manually.

**Comment by njovy** [comment]
@mraleph It's been a while since the issue was closed but I just wanted to leave a comment. Of course the library doesn't prevent sending a binary metadata but it's just a workaround and wasting bandwidth and compute power. I have been using grpc since 2018 and I edited my grpc servers to handle base64 encoded for binary data from dart grpc clients. However, ignoring what specs isn't a good practice in a long run. As the op said, nodeJS and Java grpc already have implemented this specification. I think we should leave this open for someone to pick up this issue rather than closing it. I am aware that changing Map<String, String> to Map<String, dynamic> for a metadata argument requires some changes from http2 package so we can also open an issue there to be able to support this feature. I would love to see this feature in grpc-dart as well.
